# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rinchi-Outlook
version:      0.02
version_from: lib/Rinchi/Outlook.pm
installdirs:  site
requires:
    Carp:                          1.0
    Class::ISA:                    0.30
    XML::DOM:                      1.40
    XML::Parser:                   2.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
